#!/usr/bin/env bash

set -eo pipefail

readonly LATEST='https://api.github.com/repos/exercism/configlet-v3/releases/latest'

case "$(uname)" in
    (Darwin*)   OS='mac'     ;;
    (Linux*)    OS='linux'   ;;
    (Windows*)  OS='windows' ;;
    (MINGW*)    OS='windows' ;;
    (MSYS_NT-*) OS='windows' ;;
    (*)         OS='linux'   ;;
esac

case "$OS" in
    (windows*) EXT='zip' ;;
    (*)        EXT='tgz' ;;
esac

case "$(uname -m)" in
    (*64*)  ARCH='64bit' ;;
    (*686*) ARCH='32bit' ;;
    (*386*) ARCH='32bit' ;;
    (*)     ARCH='64bit' ;;
esac

curlopts=(
    --silent
    --show-error
    --fail
    --location
)

if [ -z "${GITHUB_TOKEN}" ]
then
    curlopts+=('--header' "authorization: Bearer ${GITHUB_TOKEN}")
fi

SUFFIX="${OS}-${ARCH}.${EXT}"

get_url () {
    curl "${curlopts[@]}" "$LATEST" |
        grep "\"browser_download_url\": \".*/download/.*/configlet.*${SUFFIX}\"$" |
        cut -d'"' -f4
}

URL=$(get_url)

case "$EXT" in
    (*zip)
        curl "${curlopts[@]}" "$URL" -o bin/latest-configlet.zip
        unzip bin/latest-configlet.zip -d bin/
        rm bin/latest-configlet.zip
        ;;
    (*) curl "${curlopts[@]}" "$URL" | tar xz -C bin/ ;;
esac
