name: Lint whitespace

on: [push, pull_request, workflow_dispatch]

jobs:
  lint_whitespace:
    name: Lint whitespace
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Check that every file has no trailing whitespace, and exactly one final newline
        run: ./.github/bin/lint-whitespace
