name: markdownlint

on: [push, pull_request, workflow_dispatch]

jobs:
  markdownlint:
    name: Lint markdown files
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b
        with:
          globs: "**/*.md"
