name: shellcheck

on: [push, pull_request, workflow_dispatch]

jobs:
  shellcheck:
    name: Run shellcheck on scripts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          ignore_names: configlet.zsh
